# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 02:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ap_vkl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='handle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
