# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap_vkl', '0003_auto_20160302_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='zipcode',
            field=models.CharField(max_length=5),
        ),
    ]
