# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap_vkl', '0004_auto_20160302_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.RemoveField(
            model_name='vinyl',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=128, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='vinyl',
            name='catalog',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
